#represents the maximum distance in one direction a user may be teleported; must be an whole number (numbers under 100 are not recommended)
maxDistance: 1000

#represents the maximum number of teleports a player may use; must be a whole number
maxTeleports: 1