name: SpikeyRTP
version: 1.0
main: io.github.spikey84.spikeyrtp.Main
api-version: 1.13
commands:
  rtp:
    usage: /rtp
    description: Random teleport.
  rtpreset:
    usage: /rtpreset
    description: Resets a player's rtp data.
    permission: spikeyrtp.reset
  removebeams:
    usage: /removebeams
    description: Removes beams from end gateways within a radius of the player.
    permission: spikeyrtp.removebeams
  stuck:
    usage: /stuck
    description: Kills the user in case they are stuck
permissions:
    spikeyrtp.bypasslimit:
      default: false
      description: Allows a player to bypass the limit of rtp. Will not store rtps by this player.
    spikeyrtp.rtp:
      default: false
      description: Allows a player to run /rtp
